"""Add last page content fields

Revision ID: 114e698eb8b9
Revises: bdd26ff2189e
Create Date: 2026-01-11 07:55:58.874915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114e698eb8b9'
down_revision = 'bdd26ff2189e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_page_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_page_order_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_page_res_desc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('last_page_res_desc')
        batch_op.drop_column('last_page_order_desc')
        batch_op.drop_column('last_page_title')

    # ### end Alembic commands ###
