"""add menu embeddings

Revision ID: 12ab5c06beda
Revises: dddc3deb6a74
Create Date: 2026-02-07 00:57:04.912410

"""
from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision = '12ab5c06beda'
down_revision = 'dddc3deb6a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Enable pgvector extension (Neon/Postgres specific)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # 2. Create Menu Embeddings Table
    op.create_table('menu_embeddings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('menu_item_id', sa.Integer(), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(384), nullable=True),
        sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 3. Clean up old columns (Commented out for safety - UNCOMMENT IF SURE)
    # with op.batch_alter_table('clients', schema=None) as batch_op:
    #     batch_op.drop_column('parking_details')
    #     batch_op.drop_column('has_mushola')
    #     batch_op.drop_column('seating_capacity')
    #     batch_op.drop_column('has_restroom')
    #     batch_op.drop_column('has_kids_menu')
    #     batch_op.drop_column('accepted_payment_methods')
    #     batch_op.drop_column('has_ac')
    #     batch_op.drop_column('ai_context_rules')
    #     batch_op.drop_column('house_rules')
    #     batch_op.drop_column('ai_house_rules')
    #     batch_op.drop_column('has_outdoor_seating')
    #     batch_op.drop_column('has_baby_chair')
    #     batch_op.drop_column('whatsapp_number')
    #     batch_op.drop_column('is_wheelchair_accessible')

    # with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
    #     batch_op.alter_column('welcome_message',
    #            existing_type=sa.VARCHAR(length=200),
    #            type_=sa.Text(),
    #            existing_nullable=True)

    # with op.batch_alter_table('menu_items', schema=None) as batch_op:
    #     batch_op.alter_column('allergy_info',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    #     batch_op.alter_column('prep_time',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('prep_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('allergy_info',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('menu_embeddings', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=sa.NUMERIC(precision=1536),
               existing_nullable=True)

    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.alter_column('welcome_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_wheelchair_accessible', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('has_baby_chair', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('has_outdoor_seating', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ai_house_rules', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('house_rules', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ai_context_rules', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('has_ac', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('accepted_payment_methods', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('has_kids_menu', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('has_restroom', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('seating_capacity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('has_mushola', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('parking_details', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
