"""Add AI Provider Config fields

Revision ID: 267dc1d917e7
Revises: 764793767abc
Create Date: 2026-01-04 01:18:03.946137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267dc1d917e7'
down_revision = '764793767abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ai_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_tokens', sa.Integer(), nullable=True))
        batch_op.drop_column('model_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_config', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('max_tokens')
        batch_op.drop_column('temperature')
        batch_op.drop_column('ai_api_key')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_provider')

    # ### end Alembic commands ###
