"""add billing_note to client

Revision ID: 2d489ba35f72
Revises: d3df7c570c02
Create Date: 2026-01-04 00:06:35.101291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d489ba35f72'
down_revision = 'd3df7c570c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('billing_note')

    # ### end Alembic commands ###
