"""add extended kb columns

Revision ID: 2ef6f4e9d23f
Revises: 95572dc3929a
Create Date: 2026-01-02 01:49:50.230794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef6f4e9d23f'
down_revision = '95572dc3929a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_methods', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parking_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dietary_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('policy_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('policy_info')
        batch_op.drop_column('dietary_info')
        batch_op.drop_column('parking_info')
        batch_op.drop_column('payment_methods')

    # ### end Alembic commands ###
