"""Add Branding Billing and Guest Experience fields

Revision ID: 3fab8a4aa943
Revises: fa9e5e6be0a4
Create Date: 2026-01-05 23:14:20.904827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fab8a4aa943'
down_revision = 'fa9e5e6be0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_position', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_white_labeled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('price_includes_tax', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wifi_ssid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wifi_password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('review_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('booking_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('booking_url')
        batch_op.drop_column('review_url')
        batch_op.drop_column('wifi_password')
        batch_op.drop_column('wifi_ssid')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('price_includes_tax')
        batch_op.drop_column('is_white_labeled')
        batch_op.drop_column('widget_position')

    # ### end Alembic commands ###
