"""Add website_url and delivery_partners

Revision ID: 470ec84788e0
Revises: fd814a53c7a4
Create Date: 2026-01-05 00:09:51.222218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470ec84788e0'
down_revision = 'fd814a53c7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_partners', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('website_url')
        batch_op.drop_column('delivery_partners')

    # ### end Alembic commands ###
