"""Baseline

Revision ID: 4fd2bb980c93
Revises: 12ab5c06beda
Create Date: 2026-02-09 16:09:35.996678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fd2bb980c93'
down_revision = '12ab5c06beda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('restaurant_knowledge_embedding_idx'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')

    op.drop_table('restaurant_knowledge')
    op.drop_table('playing_with_neon')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_synced', sa.Boolean(), nullable=True))
        batch_op.alter_column('prep_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('prep_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('embedding_synced')

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.create_table('restaurant_knowledge',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_knowledge_pkey'))
    )
    with op.batch_alter_table('restaurant_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('restaurant_knowledge_embedding_idx'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')

    # ### end Alembic commands ###
