"""add slug and renewal_date

Revision ID: 6b2878176ff8
Revises: 2d489ba35f72
Create Date: 2026-01-04 00:17:12.342993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2878176ff8'
down_revision = '2d489ba35f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('renewal_date', sa.Date(), nullable=True))
        batch_op.create_unique_constraint('uq_clients_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clients_slug', type_='unique')
        batch_op.drop_column('renewal_date')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
