"""Add MenuItems and Admin Studio fields

Revision ID: 764793767abc
Revises: 6b2878176ff8
Create Date: 2026-01-04 00:43:48.603567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764793767abc'
down_revision = '6b2878176ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_maintenance_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allowed_domains', sa.Text(), nullable=True))

    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('model_config', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fallback_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('conversation_starters', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('human_handoff_triggers', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('human_handoff_triggers')
        batch_op.drop_column('conversation_starters')
        batch_op.drop_column('fallback_message')
        batch_op.drop_column('model_config')
        batch_op.drop_column('system_prompt')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('allowed_domains')
        batch_op.drop_column('is_maintenance_mode')

    op.drop_table('menu_items')
    # ### end Alembic commands ###
