"""Add Global Currency fields

Revision ID: 900d5ca3f19b
Revises: f0be5f5c69d5
Create Date: 2026-01-04 23:29:12.492823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900d5ca3f19b'
down_revision = 'f0be5f5c69d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('currency_symbol', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('currency_symbol')
        batch_op.drop_column('currency_code')

    # ### end Alembic commands ###
