"""add flow columns

Revision ID: 95572dc3929a
Revises: b83e862ba5ca
Create Date: 2026-01-02 01:35:38.606801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95572dc3929a'
down_revision = 'b83e862ba5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_menu', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flow_hours', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flow_location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flow_about', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flow_contact', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('flow_contact')
        batch_op.drop_column('flow_about')
        batch_op.drop_column('flow_location')
        batch_op.drop_column('flow_hours')
        batch_op.drop_column('flow_menu')

    # ### end Alembic commands ###
