"""Added avatar_image

Revision ID: b83e862ba5ca
Revises: cf8f783fe50e
Create Date: 2026-01-02 01:05:15.906212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83e862ba5ca'
down_revision = 'cf8f783fe50e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('avatar_image')

    # ### end Alembic commands ###
