"""Add welcome_image_url to KnowledgeBase

Revision ID: bdd26ff2189e
Revises: 3fab8a4aa943
Create Date: 2026-01-05 23:26:38.943399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd26ff2189e'
down_revision = '3fab8a4aa943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('welcome_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('welcome_image_url')

    # ### end Alembic commands ###
