"""Add Compliance Ops fields

Revision ID: cfe371fef75d
Revises: 267dc1d917e7
Create Date: 2026-01-04 01:22:48.408617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe371fef75d'
down_revision = '267dc1d917e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operating_hours', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('privacy_policy_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('privacy_policy_url')
        batch_op.drop_column('timezone')
        batch_op.drop_column('operating_hours')

    # ### end Alembic commands ###
