"""Add TOC fields to KnowledgeBase

Revision ID: dddc3deb6a74
Revises: 114e698eb8b9
Create Date: 2026-01-11 08:41:53.878669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddc3deb6a74'
down_revision = '114e698eb8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toc_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('toc_footer_text', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('toc_footer_text')
        batch_op.drop_column('toc_title')

    # ### end Alembic commands ###
