"""Add Regional and Contact fields

Revision ID: f0be5f5c69d5
Revises: cfe371fef75d
Create Date: 2026-01-04 23:23:10.015500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0be5f5c69d5'
down_revision = 'cfe371fef75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('owner_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('public_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('maps_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('maps_url')
        batch_op.drop_column('address')
        batch_op.drop_column('public_phone')
        batch_op.drop_column('owner_phone')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
