"""Fix welcome_message location

Revision ID: f9830c15b181
Revises: eb450333e7ab
Create Date: 2026-01-02 00:26:09.195741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9830c15b181'
down_revision = 'eb450333e7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('theme_color')

    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('welcome_message', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('welcome_message')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_color', sa.VARCHAR(length=7), nullable=True))

    # ### end Alembic commands ###
