"""Add owner_email and subscription dates

Revision ID: fa9e5e6be0a4
Revises: 470ec84788e0
Create Date: 2026-01-05 00:15:23.124416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9e5e6be0a4'
down_revision = '470ec84788e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('subscription_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('owner_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('owner_email')
        batch_op.drop_column('subscription_end')
        batch_op.drop_column('subscription_start')

    # ### end Alembic commands ###
