"""Add Delivery URL and Public Email

Revision ID: fd814a53c7a4
Revises: 900d5ca3f19b
Create Date: 2026-01-05 00:05:02.624133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd814a53c7a4'
down_revision = '900d5ca3f19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('delivery_url')
        batch_op.drop_column('public_email')

    # ### end Alembic commands ###
